// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AdvancePhaseResponsePhase.
const (
	AdvancePhaseResponsePhaseDiscussion     AdvancePhaseResponsePhase = "discussion"
	AdvancePhaseResponsePhaseEnding         AdvancePhaseResponsePhase = "ending"
	AdvancePhaseResponsePhaseIntro          AdvancePhaseResponsePhase = "intro"
	AdvancePhaseResponsePhaseInvestigation1 AdvancePhaseResponsePhase = "investigation1"
	AdvancePhaseResponsePhaseInvestigation2 AdvancePhaseResponsePhase = "investigation2"
	AdvancePhaseResponsePhaseVoting         AdvancePhaseResponsePhase = "voting"
)

// Defines values for CreateSessionRequestDifficulty.
const (
	Easy   CreateSessionRequestDifficulty = "easy"
	Hard   CreateSessionRequestDifficulty = "hard"
	Medium CreateSessionRequestDifficulty = "medium"
)

// Defines values for CreateSessionRequestPlayerCount.
const (
	N4 CreateSessionRequestPlayerCount = 4
	N5 CreateSessionRequestPlayerCount = 5
)

// Defines values for PhaseResponsePhase.
const (
	PhaseResponsePhaseDiscussion     PhaseResponsePhase = "discussion"
	PhaseResponsePhaseEnding         PhaseResponsePhase = "ending"
	PhaseResponsePhaseIntro          PhaseResponsePhase = "intro"
	PhaseResponsePhaseInvestigation1 PhaseResponsePhase = "investigation1"
	PhaseResponsePhaseInvestigation2 PhaseResponsePhase = "investigation2"
	PhaseResponsePhaseVoting         PhaseResponsePhase = "voting"
)

// AdvancePhaseResponse defines model for AdvancePhaseResponse.
type AdvancePhaseResponse struct {
	Phase AdvancePhaseResponsePhase `json:"phase"`
}

// AdvancePhaseResponsePhase defines model for AdvancePhaseResponse.Phase.
type AdvancePhaseResponsePhase string

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Difficulty  CreateSessionRequestDifficulty  `json:"difficulty"`
	PlayerCount CreateSessionRequestPlayerCount `json:"playerCount"`
}

// CreateSessionRequestDifficulty defines model for CreateSessionRequest.Difficulty.
type CreateSessionRequestDifficulty string

// CreateSessionRequestPlayerCount defines model for CreateSessionRequest.PlayerCount.
type CreateSessionRequestPlayerCount int

// CreateSessionResponse defines model for CreateSessionResponse.
type CreateSessionResponse struct {
	SessionId string `json:"sessionId"`
}

// JoinPlayerRequest defines model for JoinPlayerRequest.
type JoinPlayerRequest struct {
	PlayerName string `json:"playerName"`
}

// JoinPlayerResponse defines model for JoinPlayerResponse.
type JoinPlayerResponse struct {
	PlayerId string `json:"playerId"`
	RoleId   string `json:"roleId"`
}

// PhaseResponse defines model for PhaseResponse.
type PhaseResponse struct {
	GmText      string             `json:"gmText"`
	Phase       PhaseResponsePhase `json:"phase"`
	PrivateInfo *string            `json:"privateInfo"`
	PublicInfo  *string            `json:"publicInfo"`
}

// PhaseResponsePhase defines model for PhaseResponse.Phase.
type PhaseResponsePhase string

// GetSessionPhaseParams defines parameters for GetSessionPhase.
type GetSessionPhaseParams struct {
	XPlayerId string `json:"X-Player-Id"`
}

// PostSessionsJSONRequestBody defines body for PostSessions for application/json ContentType.
type PostSessionsJSONRequestBody = CreateSessionRequest

// PostSessionPlayersJSONRequestBody defines body for PostSessionPlayers for application/json ContentType.
type PostSessionPlayersJSONRequestBody = JoinPlayerRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostSessionsWithBody request with any body
	PostSessionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSessions(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionAdvance request
	PostSessionAdvance(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSessionPhase request
	GetSessionPhase(ctx context.Context, sessionId string, params *GetSessionPhaseParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionPlayersWithBody request with any body
	PostSessionPlayersWithBody(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSessionPlayers(ctx context.Context, sessionId string, body PostSessionPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostSessionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessions(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessionAdvance(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionAdvanceRequest(c.Server, sessionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSessionPhase(ctx context.Context, sessionId string, params *GetSessionPhaseParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSessionPhaseRequest(c.Server, sessionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessionPlayersWithBody(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionPlayersRequestWithBody(c.Server, sessionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessionPlayers(ctx context.Context, sessionId string, body PostSessionPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionPlayersRequest(c.Server, sessionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostSessionsRequest calls the generic PostSessions builder with application/json body
func NewPostSessionsRequest(server string, body PostSessionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSessionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSessionsRequestWithBody generates requests for PostSessions with any type of body
func NewPostSessionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostSessionAdvanceRequest generates requests for PostSessionAdvance
func NewPostSessionAdvanceRequest(server string, sessionId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sessionId", runtime.ParamLocationPath, sessionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions/%s/advance", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSessionPhaseRequest generates requests for GetSessionPhase
func NewGetSessionPhaseRequest(server string, sessionId string, params *GetSessionPhaseParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sessionId", runtime.ParamLocationPath, sessionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions/%s/phase", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Player-Id", runtime.ParamLocationHeader, params.XPlayerId)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Player-Id", headerParam0)

	}

	return req, nil
}

// NewPostSessionPlayersRequest calls the generic PostSessionPlayers builder with application/json body
func NewPostSessionPlayersRequest(server string, sessionId string, body PostSessionPlayersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSessionPlayersRequestWithBody(server, sessionId, "application/json", bodyReader)
}

// NewPostSessionPlayersRequestWithBody generates requests for PostSessionPlayers with any type of body
func NewPostSessionPlayersRequestWithBody(server string, sessionId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sessionId", runtime.ParamLocationPath, sessionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions/%s/players", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostSessionsWithBodyWithResponse request with any body
	PostSessionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error)

	PostSessionsWithResponse(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error)

	// PostSessionAdvanceWithResponse request
	PostSessionAdvanceWithResponse(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*PostSessionAdvanceResponse, error)

	// GetSessionPhaseWithResponse request
	GetSessionPhaseWithResponse(ctx context.Context, sessionId string, params *GetSessionPhaseParams, reqEditors ...RequestEditorFn) (*GetSessionPhaseResponse, error)

	// PostSessionPlayersWithBodyWithResponse request with any body
	PostSessionPlayersWithBodyWithResponse(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionPlayersResponse, error)

	PostSessionPlayersWithResponse(ctx context.Context, sessionId string, body PostSessionPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionPlayersResponse, error)
}

type PostSessionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateSessionResponse
}

// Status returns HTTPResponse.Status
func (r PostSessionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSessionAdvanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AdvancePhaseResponse
}

// Status returns HTTPResponse.Status
func (r PostSessionAdvanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionAdvanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSessionPhaseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PhaseResponse
}

// Status returns HTTPResponse.Status
func (r GetSessionPhaseResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSessionPhaseResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSessionPlayersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JoinPlayerResponse
}

// Status returns HTTPResponse.Status
func (r PostSessionPlayersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionPlayersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostSessionsWithBodyWithResponse request with arbitrary body returning *PostSessionsResponse
func (c *ClientWithResponses) PostSessionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error) {
	rsp, err := c.PostSessionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionsResponse(rsp)
}

func (c *ClientWithResponses) PostSessionsWithResponse(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error) {
	rsp, err := c.PostSessions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionsResponse(rsp)
}

// PostSessionAdvanceWithResponse request returning *PostSessionAdvanceResponse
func (c *ClientWithResponses) PostSessionAdvanceWithResponse(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*PostSessionAdvanceResponse, error) {
	rsp, err := c.PostSessionAdvance(ctx, sessionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionAdvanceResponse(rsp)
}

// GetSessionPhaseWithResponse request returning *GetSessionPhaseResponse
func (c *ClientWithResponses) GetSessionPhaseWithResponse(ctx context.Context, sessionId string, params *GetSessionPhaseParams, reqEditors ...RequestEditorFn) (*GetSessionPhaseResponse, error) {
	rsp, err := c.GetSessionPhase(ctx, sessionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSessionPhaseResponse(rsp)
}

// PostSessionPlayersWithBodyWithResponse request with arbitrary body returning *PostSessionPlayersResponse
func (c *ClientWithResponses) PostSessionPlayersWithBodyWithResponse(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionPlayersResponse, error) {
	rsp, err := c.PostSessionPlayersWithBody(ctx, sessionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionPlayersResponse(rsp)
}

func (c *ClientWithResponses) PostSessionPlayersWithResponse(ctx context.Context, sessionId string, body PostSessionPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionPlayersResponse, error) {
	rsp, err := c.PostSessionPlayers(ctx, sessionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionPlayersResponse(rsp)
}

// ParsePostSessionsResponse parses an HTTP response from a PostSessionsWithResponse call
func ParsePostSessionsResponse(rsp *http.Response) (*PostSessionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateSessionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSessionAdvanceResponse parses an HTTP response from a PostSessionAdvanceWithResponse call
func ParsePostSessionAdvanceResponse(rsp *http.Response) (*PostSessionAdvanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionAdvanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AdvancePhaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSessionPhaseResponse parses an HTTP response from a GetSessionPhaseWithResponse call
func ParseGetSessionPhaseResponse(rsp *http.Response) (*GetSessionPhaseResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSessionPhaseResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PhaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSessionPlayersResponse parses an HTTP response from a PostSessionPlayersWithResponse call
func ParsePostSessionPlayersResponse(rsp *http.Response) (*PostSessionPlayersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionPlayersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JoinPlayerResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create new game session
	// (POST /sessions)
	PostSessions(ctx echo.Context) error
	// Advance game phase (GM use)
	// (POST /sessions/{sessionId}/advance)
	PostSessionAdvance(ctx echo.Context, sessionId string) error
	// Get current phase information
	// (GET /sessions/{sessionId}/phase)
	GetSessionPhase(ctx echo.Context, sessionId string, params GetSessionPhaseParams) error
	// Join a game session
	// (POST /sessions/{sessionId}/players)
	PostSessionPlayers(ctx echo.Context, sessionId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostSessions converts echo context to params.
func (w *ServerInterfaceWrapper) PostSessions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSessions(ctx)
	return err
}

// PostSessionAdvance converts echo context to params.
func (w *ServerInterfaceWrapper) PostSessionAdvance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", ctx.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSessionAdvance(ctx, sessionId)
	return err
}

// GetSessionPhase converts echo context to params.
func (w *ServerInterfaceWrapper) GetSessionPhase(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", ctx.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSessionPhaseParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Player-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Player-Id")]; found {
		var XPlayerId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Player-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Player-Id", valueList[0], &XPlayerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Player-Id: %s", err))
		}

		params.XPlayerId = XPlayerId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Player-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSessionPhase(ctx, sessionId, params)
	return err
}

// PostSessionPlayers converts echo context to params.
func (w *ServerInterfaceWrapper) PostSessionPlayers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", ctx.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSessionPlayers(ctx, sessionId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/sessions", wrapper.PostSessions)
	router.POST(baseURL+"/sessions/:sessionId/advance", wrapper.PostSessionAdvance)
	router.GET(baseURL+"/sessions/:sessionId/phase", wrapper.GetSessionPhase)
	router.POST(baseURL+"/sessions/:sessionId/players", wrapper.PostSessionPlayers)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWXWsjNxT9K+K2Dy3IHjvbwjJv7kKDCynDbimFbVgU6dpWOvpY6Y67Jvi/F0nj2BlP",
	"Gj80S9+E5ujq6Bzdo3kA6Yx3Fi1FqB8gyg0akYcLtRVWYrMREd9j9M5GTPM+OI+BNGaUT5/TAG1noP4I",
	"2lJwwEHbLUbSa0Ha2flw4go4KB1lF6N2FjhsHWm7Bg5oVRrccqCdR6ghUkgT+z2HgJ87HVClfcrGR5i7",
	"u0dJsOfwLqAg/IC59Hv83GGkc+JKr1Zadi3tTtmjiDvgYFDpzgCHjQhqhAsH34odhneus3Sy/gf+4xGs",
	"LeEawznzk6X8lMcFh3nOhlgAS5XJfBHGt5lvmf40v3oDLwl6LDHG4xenbZOJP6toOdevwuBTEmUZW7zI",
	"4KTASxSevY75+1CGMvtpDiNGBtfiGX5+IdelgscKY5RfaJ61+Q2/ZCXP79dX6ysOPuitIFzalUs72q5t",
	"xV0SgkKHY/jurtXyQvho2/LD0c9FSwt0X1phlEH7dDCo4eb3ht0J+RdaxRbNkq1cYIvlZI0WgyBUzHRB",
	"YWBmFwnDjq2FwSn7WUickJushESWXOPMaKuNaBla5Z22FKd/JqlIU3b/ppS56cukbRfNMmmJIRYqs+l8",
	"OktSOI9WeA01vJnOpqnJvKBNNrfqG6rcS1c6JrmfjUpXDhoX6cMBVXTCSD85lTNJOktY4kV432qZF1b3",
	"MVE4RHUafRtwBTV8Ux2zvOqDvBoNw/1TV5JveaLc00z4ajZ7LQ59N2QSTx3uIUzmBSpfntgZI8IO6j4K",
	"mcW/s7Ws1zejHsWuHh5zbF+J8oRdZED/3GUHgzBIGCLUHx9AJ2bJVeBgc7idROVQRn4iybARbl9R4tHH",
	"ekThDGC9LkOB+yJF3dyo7LvrG9ZF/P5fRH5MqjWOKHyNB4GbvvNfS17e19qgUBiO1f6YlEdj8j+y60Kf",
	"Ug4GkzcYWHWNxGQXAlrqnRpinzErS3FZJDU99pU74r/PvPN/la8ceCN/KmMel/+ie6ftWSumCkwMcy5B",
	"MGwPPnShTfedyNdV1Top2o2LVL+dvZ3B/nb/TwAAAP//ukbjbdwLAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
