// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateSessionRequestDifficulty.
const (
	Easy   CreateSessionRequestDifficulty = "easy"
	Hard   CreateSessionRequestDifficulty = "hard"
	Medium CreateSessionRequestDifficulty = "medium"
)

// Defines values for CreateSessionRequestPlayerCount.
const (
	N4 CreateSessionRequestPlayerCount = 4
	N5 CreateSessionRequestPlayerCount = 5
)

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Difficulty  CreateSessionRequestDifficulty  `json:"difficulty"`
	PlayerCount CreateSessionRequestPlayerCount `json:"playerCount"`
}

// CreateSessionRequestDifficulty defines model for CreateSessionRequest.Difficulty.
type CreateSessionRequestDifficulty string

// CreateSessionRequestPlayerCount defines model for CreateSessionRequest.PlayerCount.
type CreateSessionRequestPlayerCount int

// CreateSessionResponse defines model for CreateSessionResponse.
type CreateSessionResponse struct {
	SessionId *string `json:"sessionId,omitempty"`
}

// JoinPlayerRequest defines model for JoinPlayerRequest.
type JoinPlayerRequest struct {
	PlayerName string `json:"playerName"`
}

// JoinPlayerResponse defines model for JoinPlayerResponse.
type JoinPlayerResponse struct {
	PlayerId *string `json:"playerId,omitempty"`
	RoleId   *string `json:"roleId,omitempty"`
}

// PhaseResponse defines model for PhaseResponse.
type PhaseResponse struct {
	GmText      *string `json:"gmText,omitempty"`
	PrivateInfo *string `json:"privateInfo,omitempty"`
	PublicInfo  *string `json:"publicInfo,omitempty"`
}

// GetSessionsSessionIdPhaseParams defines parameters for GetSessionsSessionIdPhase.
type GetSessionsSessionIdPhaseParams struct {
	XPlayerId string `json:"X-Player-Id"`
}

// PostSessionsJSONRequestBody defines body for PostSessions for application/json ContentType.
type PostSessionsJSONRequestBody = CreateSessionRequest

// PostSessionsSessionIdPlayersJSONRequestBody defines body for PostSessionsSessionIdPlayers for application/json ContentType.
type PostSessionsSessionIdPlayersJSONRequestBody = JoinPlayerRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostSessionsWithBody request with any body
	PostSessionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSessions(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionsSessionIdAdvance request
	PostSessionsSessionIdAdvance(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSessionsSessionIdPhase request
	GetSessionsSessionIdPhase(ctx context.Context, sessionId string, params *GetSessionsSessionIdPhaseParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSessionsSessionIdPlayersWithBody request with any body
	PostSessionsSessionIdPlayersWithBody(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSessionsSessionIdPlayers(ctx context.Context, sessionId string, body PostSessionsSessionIdPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostSessionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessions(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessionsSessionIdAdvance(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionsSessionIdAdvanceRequest(c.Server, sessionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSessionsSessionIdPhase(ctx context.Context, sessionId string, params *GetSessionsSessionIdPhaseParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSessionsSessionIdPhaseRequest(c.Server, sessionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessionsSessionIdPlayersWithBody(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionsSessionIdPlayersRequestWithBody(c.Server, sessionId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSessionsSessionIdPlayers(ctx context.Context, sessionId string, body PostSessionsSessionIdPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSessionsSessionIdPlayersRequest(c.Server, sessionId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostSessionsRequest calls the generic PostSessions builder with application/json body
func NewPostSessionsRequest(server string, body PostSessionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSessionsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSessionsRequestWithBody generates requests for PostSessions with any type of body
func NewPostSessionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostSessionsSessionIdAdvanceRequest generates requests for PostSessionsSessionIdAdvance
func NewPostSessionsSessionIdAdvanceRequest(server string, sessionId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sessionId", runtime.ParamLocationPath, sessionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions/%s/advance", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSessionsSessionIdPhaseRequest generates requests for GetSessionsSessionIdPhase
func NewGetSessionsSessionIdPhaseRequest(server string, sessionId string, params *GetSessionsSessionIdPhaseParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sessionId", runtime.ParamLocationPath, sessionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions/%s/phase", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Player-Id", runtime.ParamLocationHeader, params.XPlayerId)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Player-Id", headerParam0)

	}

	return req, nil
}

// NewPostSessionsSessionIdPlayersRequest calls the generic PostSessionsSessionIdPlayers builder with application/json body
func NewPostSessionsSessionIdPlayersRequest(server string, sessionId string, body PostSessionsSessionIdPlayersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSessionsSessionIdPlayersRequestWithBody(server, sessionId, "application/json", bodyReader)
}

// NewPostSessionsSessionIdPlayersRequestWithBody generates requests for PostSessionsSessionIdPlayers with any type of body
func NewPostSessionsSessionIdPlayersRequestWithBody(server string, sessionId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "sessionId", runtime.ParamLocationPath, sessionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sessions/%s/players", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostSessionsWithBodyWithResponse request with any body
	PostSessionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error)

	PostSessionsWithResponse(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error)

	// PostSessionsSessionIdAdvanceWithResponse request
	PostSessionsSessionIdAdvanceWithResponse(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*PostSessionsSessionIdAdvanceResponse, error)

	// GetSessionsSessionIdPhaseWithResponse request
	GetSessionsSessionIdPhaseWithResponse(ctx context.Context, sessionId string, params *GetSessionsSessionIdPhaseParams, reqEditors ...RequestEditorFn) (*GetSessionsSessionIdPhaseResponse, error)

	// PostSessionsSessionIdPlayersWithBodyWithResponse request with any body
	PostSessionsSessionIdPlayersWithBodyWithResponse(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionsSessionIdPlayersResponse, error)

	PostSessionsSessionIdPlayersWithResponse(ctx context.Context, sessionId string, body PostSessionsSessionIdPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionsSessionIdPlayersResponse, error)
}

type PostSessionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateSessionResponse
}

// Status returns HTTPResponse.Status
func (r PostSessionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSessionsSessionIdAdvanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostSessionsSessionIdAdvanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionsSessionIdAdvanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSessionsSessionIdPhaseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PhaseResponse
}

// Status returns HTTPResponse.Status
func (r GetSessionsSessionIdPhaseResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSessionsSessionIdPhaseResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSessionsSessionIdPlayersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JoinPlayerResponse
}

// Status returns HTTPResponse.Status
func (r PostSessionsSessionIdPlayersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSessionsSessionIdPlayersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostSessionsWithBodyWithResponse request with arbitrary body returning *PostSessionsResponse
func (c *ClientWithResponses) PostSessionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error) {
	rsp, err := c.PostSessionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionsResponse(rsp)
}

func (c *ClientWithResponses) PostSessionsWithResponse(ctx context.Context, body PostSessionsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionsResponse, error) {
	rsp, err := c.PostSessions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionsResponse(rsp)
}

// PostSessionsSessionIdAdvanceWithResponse request returning *PostSessionsSessionIdAdvanceResponse
func (c *ClientWithResponses) PostSessionsSessionIdAdvanceWithResponse(ctx context.Context, sessionId string, reqEditors ...RequestEditorFn) (*PostSessionsSessionIdAdvanceResponse, error) {
	rsp, err := c.PostSessionsSessionIdAdvance(ctx, sessionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionsSessionIdAdvanceResponse(rsp)
}

// GetSessionsSessionIdPhaseWithResponse request returning *GetSessionsSessionIdPhaseResponse
func (c *ClientWithResponses) GetSessionsSessionIdPhaseWithResponse(ctx context.Context, sessionId string, params *GetSessionsSessionIdPhaseParams, reqEditors ...RequestEditorFn) (*GetSessionsSessionIdPhaseResponse, error) {
	rsp, err := c.GetSessionsSessionIdPhase(ctx, sessionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSessionsSessionIdPhaseResponse(rsp)
}

// PostSessionsSessionIdPlayersWithBodyWithResponse request with arbitrary body returning *PostSessionsSessionIdPlayersResponse
func (c *ClientWithResponses) PostSessionsSessionIdPlayersWithBodyWithResponse(ctx context.Context, sessionId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSessionsSessionIdPlayersResponse, error) {
	rsp, err := c.PostSessionsSessionIdPlayersWithBody(ctx, sessionId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionsSessionIdPlayersResponse(rsp)
}

func (c *ClientWithResponses) PostSessionsSessionIdPlayersWithResponse(ctx context.Context, sessionId string, body PostSessionsSessionIdPlayersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSessionsSessionIdPlayersResponse, error) {
	rsp, err := c.PostSessionsSessionIdPlayers(ctx, sessionId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSessionsSessionIdPlayersResponse(rsp)
}

// ParsePostSessionsResponse parses an HTTP response from a PostSessionsWithResponse call
func ParsePostSessionsResponse(rsp *http.Response) (*PostSessionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateSessionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSessionsSessionIdAdvanceResponse parses an HTTP response from a PostSessionsSessionIdAdvanceWithResponse call
func ParsePostSessionsSessionIdAdvanceResponse(rsp *http.Response) (*PostSessionsSessionIdAdvanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionsSessionIdAdvanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetSessionsSessionIdPhaseResponse parses an HTTP response from a GetSessionsSessionIdPhaseWithResponse call
func ParseGetSessionsSessionIdPhaseResponse(rsp *http.Response) (*GetSessionsSessionIdPhaseResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSessionsSessionIdPhaseResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PhaseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostSessionsSessionIdPlayersResponse parses an HTTP response from a PostSessionsSessionIdPlayersWithResponse call
func ParsePostSessionsSessionIdPlayersResponse(rsp *http.Response) (*PostSessionsSessionIdPlayersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSessionsSessionIdPlayersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JoinPlayerResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new game session
	// (POST /sessions)
	PostSessions(ctx echo.Context) error
	// Advance to the next phase
	// (POST /sessions/{sessionId}/advance)
	PostSessionsSessionIdAdvance(ctx echo.Context, sessionId string) error
	// Get current phase info
	// (GET /sessions/{sessionId}/phase)
	GetSessionsSessionIdPhase(ctx echo.Context, sessionId string, params GetSessionsSessionIdPhaseParams) error
	// Join Session
	// (POST /sessions/{sessionId}/players)
	PostSessionsSessionIdPlayers(ctx echo.Context, sessionId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostSessions converts echo context to params.
func (w *ServerInterfaceWrapper) PostSessions(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSessions(ctx)
	return err
}

// PostSessionsSessionIdAdvance converts echo context to params.
func (w *ServerInterfaceWrapper) PostSessionsSessionIdAdvance(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", ctx.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSessionsSessionIdAdvance(ctx, sessionId)
	return err
}

// GetSessionsSessionIdPhase converts echo context to params.
func (w *ServerInterfaceWrapper) GetSessionsSessionIdPhase(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", ctx.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSessionsSessionIdPhaseParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Player-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Player-Id")]; found {
		var XPlayerId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Player-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Player-Id", valueList[0], &XPlayerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Player-Id: %s", err))
		}

		params.XPlayerId = XPlayerId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Player-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSessionsSessionIdPhase(ctx, sessionId, params)
	return err
}

// PostSessionsSessionIdPlayers converts echo context to params.
func (w *ServerInterfaceWrapper) PostSessionsSessionIdPlayers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", ctx.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sessionId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSessionsSessionIdPlayers(ctx, sessionId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/sessions", wrapper.PostSessions)
	router.POST(baseURL+"/sessions/:sessionId/advance", wrapper.PostSessionsSessionIdAdvance)
	router.GET(baseURL+"/sessions/:sessionId/phase", wrapper.GetSessionsSessionIdPhase)
	router.POST(baseURL+"/sessions/:sessionId/players", wrapper.PostSessionsSessionIdPlayers)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVQW/bPAz9KwK/76jG2bpdfOt6KDqgQ7DsMKDoQZWZRIUtqRLV1Qj83wfJSpMmStcB",
	"7W62RYqP7/HRa5Cms0ajJg/1GrxcYSfS47lDQThH75XR3/E+oKf43Tpj0ZHCFNWoxULJ0FIf31CHDupr",
	"QOF74NBho0IHHFbCNXDDgXqLUIMnp/QSBg62FT26cxM07eR/4p+3wUoTLtHBMHBweB+UwybW2E3luzi2",
	"qeb2DiXFOnvNeGu0x8Nu/Bhw2cSXPbBD4dqvRulZwnGUoBHmN9Fh+c7DllLszR+qHetgvKLYAAdnWnx1",
	"b7OV8Hi80LL7gY9ULGOdehCEl3phyufhtlXyyPEhlPhJbYIVtfHsKrgGHbvqPaHr2dnsEjg8oIvqQQ0f",
	"JtPJNJYyFrWwCmo4nUwnp8DBClqlBqos9kibGbWLHQrKIwAz42m+iRqlQk9fTJOGXRpNOM6tsLZVMiVW",
	"dz5C2FgpPv3vcAE1/FdtvVZlo1VFlw3PB4NcwPRh1CIB/jidvheGrHgC0aCXTlkaab0QHbJMG5Mpq2E+",
	"SIneL0Lb9kk+H7pOuB7q7DommMZfbLmTnOKeBKjWT74bKtE8CC3xdaLMN3lnOSvq60SHhM5Dfb0GFXFH",
	"zYGDTibcMfk+yXyHsP2xvCkLUCAod/AiMxkvI8NohUzjIzEbDfcCM+N5tB4WaLnAQ1aShd+RE57vWqFo",
	"0G1v+3kyrqmTt+H4TYb8+TorDPd5cA51loGlhfNcswskJstBRwRLJPi/HOVZznrnUX77VXb4M/zHe6zw",
	"fyzoPEawO6P0yx6N17H508Iaht8BAAD//x/RILwtCQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
